// Re-export all types from the protocol package.
// This file exists for backward compatibility — downstream code that
// imports from "@uncaged/workflow-runtime" continues to work.

export type {
  AdapterBinding,
  AdapterFn,
  AdvanceOutcome,
  AgentBinding,
  AgentContext,
  AgentFn,
  AgentFnResult,
  CasStore,
  ExtractFn,
  ExtractResult,
  FALLBACK,
  LlmProvider,
  ModeratorCondition,
  ModeratorContext,
  ModeratorTable,
  ModeratorTransition,
  ProviderConfig,
  ResolvedModel,
  Result,
  RoleDefinition,
  RoleFn,
  RoleResult,
  RoleMeta,
  RoleOutput,
  RoleStep,
  StartStep,
  ThreadContext,
  WorkflowCompletion,
  WorkflowDefinition,
  WorkflowDescriptor,
  WorkflowFn,
  WorkflowGraph,
  WorkflowGraphEdge,
  WorkflowResult,
  WorkflowRoleDescriptor,
  WorkflowRoleSchema,
  WorkflowRuntime,
} from "@uncaged/workflow-protocol";

export { END, START } from "@uncaged/workflow-protocol";
